version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "watermark-image-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ebkilgu0mbna"
s3_prefix = "watermark-image-server"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
